name: Type checking

on:
  pull_request:
  push:
    branches: [main]

jobs:
  mypy:
    strategy:
      matrix:
        python-version: ["3.11"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: "true"
          cache-suffix: ${{ matrix.python-version }}
          cache-dependency-glob: "pyproject.toml"
      - name: Create venv
        run: |
         uv -m venv .venv
          source .venv/bin/activate
      - name: install-reqs
        # Python3.8 is technically at end-of-life, so we don't test everything
        run: uv pip install -e ".[dev, core]" --system
      - name: show-deps
        run: uv pip freeze
      - name: Run pytest
        run: |
          which mypy
          make typing
